Add github version of pi

diff --git a/.local/bin/pi b/.local/bin/pi
--- a/.local/bin/pi
+++ b/.local/bin/pi
@@ -1,23 +1,25 @@
 #!/bin/bash
 
-# Determine the image's MIME tyoe
-MIME_TYPE=$(wl-paste -l | grep -E '^image/(png|jpeg|gif)' | head -n 1)
+MIME_TYPE=$(wl-paste -l | grep -E '^image/(png|jpeg|gif|bmp)' | head -n 1)
+SAVE_DIR="$HOME/Screenshots"
+
+if [ -n "$1" ]; then
+    SAVE_DIR="$1"
+fi
 
 if [ -z "$MIME_TYPE" ]; then
     echo "No image found on the clipboard." >&2
     exit 1
 fi
 
-mkdir -p "$HOME/Screenshots"
+mkdir -p "$SAVE_DIR"
+if [ ! -d "$SAVE_DIR" ]; then
+    echo "Could not create directory $SAVE_DIR." >&2
+    exit 1
+fi
 
-# Determine the file extension
 EXTENSION="${MIME_TYPE#image/}"
-# Create a unique filename using the current date and time
-#
-FILENAME="screenshot_$(date +'%Y-%m-%d_%H-%M-%S').$EXTENSION"
+FILENAME="paste_image_$(date +'%Y-%m-%d_%H-%M-%S').$EXTENSION"
+wl-paste -t $MIME_TYPE > "$SAVE_DIR/$FILENAME"
 
-# Save the image from the clipboard to the file
-wl-paste -t $MIME_TYPE > "$HOME/Screenshots/$FILENAME"
-
-# Optional: Send a notification to confirm the save
-echo "Saved as $FILENAME in ~/Screenshots"
+echo "Saved as $FILENAME in $SAVE_DIR"
